-- Create table for PDP Advance Training feedback submissions
create table pdp_advance_training_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Isian
  full_name text not null,
  company_name text not null,
  division_role text,
  email text,
  phone_number text,

  -- Option (sangat baik, baik, cukup, kurang, sangat kurang)
  opt_materi_kesesuaian text,
  opt_trainer_kemampuan text,
  opt_materi_kualitas text,
  opt_metode_penyampaian text,
  opt_fasilitas_media text,
  opt_efektivitas_penyampaian text,
  opt_tingkat_pemahaman text,
  opt_kepuasan_keseluruhan text,

  -- Ya/Tidak
  yt_kebutuhan_layanan text,
  yt_bersedia_info text,
  yt_bersedia_dokumentasi text,

  -- Uraian/Isian
  ur_kritik_saran text,
  ur_hal_baik text,
  ur_saran_selanjutnya text,
  ur_kebutuhan_topik text
);

-- Enable RLS
alter table pdp_advance_training_feedback enable row level security;

-- Allow inserts from anyone (anon)
create policy "Enable insert for everyone" on pdp_advance_training_feedback for insert with check (true);

-- Allow select only for authenticated (if needed, or just admin)
create policy "Enable read access for authenticated users only" on pdp_advance_training_feedback for select using (auth.role() = 'authenticated');
